FROM postgres:latest

# Определение переменных окружения
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB mydb

# Копирование SQL-скрипта для инициализации базы данных
COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432